import type { StaticShortcutMap } from 'unocss';

export const FLEX: StaticShortcutMap = {
  row: 'flex flex-row items-center',
  'row-reverse': 'flex flex-row-reverse items-center',
  'row-stretch': 'row items-stretch',
  'row-wrap': 'flex flex-row items-center flex-wrap',
  'row-start': 'flex flex-row items-start',
  'row-end': 'flex flex-row items-end',
  'row-start-end': 'row-start justify-end',
  'row-space': 'row justify-between',
  'row-start-space': 'row-start justify-between',
  'row-stretch-space': 'row items-stretch justify-between',
  'row-start-space-reverse':
    'flex flex-row-reverse items-start justify-between',
  'row-base': 'flex flex-row items-baseline',
  column: 'flex flex-col items-center',
  'column-reverse': 'flex flex-col-reverse items-center',
  'column-stretch': 'column items-stretch',
  'column-start': 'flex flex-col items-start',
  'column-start-stretch': 'column-start items-stretch',
  'column-end': 'flex flex-col items-end',
  'column-end-reverse': 'flex flex-col-reverse items-end',
  'column-start-end': 'column-start justify-end',
  'column-center-end': 'column justify-end',
  'column-start-center': 'column-start justify-center',
  'column-space': 'column justify-between',
  center: 'flex items-center justify-center',
  'gap-box': 'gap-6',
  'gap-box-1_5': 'gap-8',
  'gap-box-2': 'gap-12',
};
